### All Orders

GET {{WP_URL}}/wp-json/wc/v3/orders
Authorization: Basic {{WP_CONSUMER_KEY}} {{WP_CONSUMER_SECRET}}

### Retrieve an Order

GET {{WP_URL}}/wp-json/wc/v3/orders/42
Authorization: Basic {{WP_CONSUMER_KEY}} {{WP_CONSUMER_SECRET}}

### Create an Order

POST {{WP_URL}}/wp-json/wc/v3/orders
Authorization: Basic {{WP_CONSUMER_KEY}} {{WP_CONSUMER_SECRET}}
Content-Type: application/json

{
    "status": "pending",
    "currency": "BRL",
    "customer_id": 4,
    "line_items": [
        {
            "sku": "lohl-commerce-parcela",
            "name": "Lohl Commerce Parcela 4/12",
            "quantity": 1,
            "total": "300.00"
        },
        {
            "sku": "juros",
            "name": "Juros",
            "quantity": 1,
            "total": "9.99"
        },
        {
            "sku": "multa",
            "name": "Multa",
            "quantity": 1,
            "total": "1.99"
        }
    ],
    "billing": {
        "first_name": "Carlos",
        "last_name": "Rodrigues Boff",
        "company": "",
        "address_1": "Rua José Luiz Marcelino, 472",
        "address_2": "apto 403",
        "city": "Itajaí",
        "state": "SC",
        "postcode": "88311-300",
        "country": "BR",
        "email": "teste@lohl.com.br",
        "phone": "",
        "persontype": "M"
    },
    "shipping": {
        "first_name": "Carlos",
        "last_name": "Rodrigues Boff",
        "company": "",
        "address_1": "Rua José Luiz Marcelino, 472",
        "address_2": "apto 403",
        "city": "Itajaí",
        "state": "SC",
        "postcode": "88311-300",
        "country": "BR",
        "phone": "",
        "number": ""
    },
    "meta_data": [
        {
            "key": "_billing_cellphone",
            "value": "(47) 99205-5398"
        },
        {
            "key": "_billing_cnpj",
            "value": ""
        },
        {
            "key": "_billing_cpf",
            "value": "817.891.159-06"
        },
        {
            "key": "_billing_neighborhood",
            "value": "Murta"
        },
        {
            "key": "_billing_number",
            "value": "472"
        },
        {
            "key": "_billing_persontype",
            "value": "1"
        },
        {
            "key": "_shipping_neighborhood",
            "value": "Murta"
        },
        {
            "key": "_shipping_number",
            "value": "472"
        }
    ]
}
