<?php

namespace App\Actions;

use App\Traits\HasActionSet;

class DefaultAction extends Action
{
    use HasActionSet;

    protected function setParams($params = []): void
    {
        parent::setParams($params); // TODO: Change the autogenerated stub
    }

    protected function handle()
    {
        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
