<?php

namespace App\Actions\Api;

use App\Actions\Action;
use App\Traits\HasActionSet;

class GenerateBillings extends Action
{
    use HasActionSet;

    protected function setParams($params = []): void
    {
        parent::setParams($params); // TODO: Change the autogenerated stub
    }

    protected function handle()
    {
        // busca por contratos ativos

        //
    }
}
